[theme]
primaryColor = "#1F77B4"             # bleu saturé pour boutons
backgroundColor = "#2F2F2F"          # fond principal légèrement gris
secondaryBackgroundColor = "#5D5D5D" # sidebar, encadrés
textColor = "#E8EAED"                 # texte sombre
font = "sans serif"