[theme]
primaryColor = "#1F77B4"             # bleu saturé pour boutons
backgroundColor = "#BBC1CC"          # fond principal légèrement gris
secondaryBackgroundColor = "#E8EAED" # sidebar, encadrés
textColor = "#111111"                 # texte sombre
font = "sans serif"